import type { TransformationOption } from './types';

export const TRANSFORMATION_OPTIONS: TransformationOption[] = [
  { label: 'Baby', prompt: 'Transform the person in the image to look like a cute baby.' },
  { label: 'Old', prompt: 'Make the person in the image look very old, with wrinkles and gray hair.' },
  { label: 'Superhero', prompt: 'Transform the person in the image into a powerful superhero with a costume and a dynamic background.' },
  { label: 'Cartoon', prompt: 'Redraw the person in the image in a colorful, friendly cartoon style.' },
  { label: 'Male', prompt: 'Transform the person in the image into a male version.' },
  { label: 'Female', prompt: 'Transform the person in the image into a female version.' },
  { label: 'Superstar', prompt: 'Transform the person in the image into a glamorous superstar on a red carpet with paparazzi flashes.' },
  { label: 'Viking', prompt: 'Transform the person in the image into a fierce Viking warrior with a beard and armor.' },
  { label: 'Astronaut', prompt: 'Place the person in the image in an astronaut suit with a nebula in the background.' },
  { label: 'Cyberpunk', prompt: 'Transform the person in the image into a cyberpunk character with neon lights and futuristic implants.' },
  { label: 'Steampunk', prompt: 'Reimagine the person in the image in a steampunk style, with gears, goggles, and Victorian-era clothing.' },
  { label: 'Renaissance', prompt: 'Turn the image of the person into a classical Renaissance oil painting.' },
  { label: 'Zombie', prompt: 'Transform the person in the image into a creepy zombie with pale skin and tattered clothes.' },
  { label: 'Fairy', prompt: 'Transform the person in the image into a magical fairy with glowing wings and a forest background.' },
  { label: 'Anime', prompt: 'Redraw the person in the image in a vibrant Japanese anime style with large eyes.' },
  { label: 'Pop Art', prompt: 'Recreate the image in the style of Andy Warhol pop art, with bold colors and repeated patterns.' },
  { label: 'Vampire', prompt: 'Turn the person in the image into an elegant vampire with fangs and a gothic setting.' },
  { label: 'Cyborg', prompt: 'Transform the person into a cyborg, blending human and machine parts seamlessly.' },
  { label: 'Elf', prompt: 'Reimagine the person as a mystical elf with pointed ears and an enchanted forest backdrop.' },
  { label: 'Pixel Art', prompt: 'Convert the image into an 8-bit pixel art style, like an old video game character.' },
  { label: 'Sketch', prompt: 'Turn the photo into a detailed pencil sketch on textured paper.' },
  { label: 'Watercolor', prompt: 'Transform the image into a beautiful watercolor painting with soft, blended colors.' },
  { label: 'Pirate', prompt: 'Transform the person in the image into a rugged pirate with an eyepatch and a pirate hat.' },
  { label: 'Mime', prompt: 'Turn the person in the image into a classic mime artist with white face paint and striped shirt.' },
  { label: 'Ghost', prompt: 'Make the person in the image look like a spooky, translucent ghost.' },
  { label: 'Gamer', prompt: 'Reimagine the person as a pro gamer with a headset and a neon-lit gaming room background.' },
  { label: 'Chef', prompt: 'Transform the person into a professional chef wearing a chef\'s hat and holding a cooking utensil.' },
  { label: 'Detective', prompt: 'Turn the person into a classic film noir detective with a fedora and a trench coat.' },
  { label: 'Rockstar', prompt: 'Make the person look like a rockstar on stage with a guitar and wild hair.' },
  { label: 'Manga', prompt: 'Redraw the person in a dramatic black and white manga art style.' },
  { label: 'Claymation', prompt: 'Recreate the image of the person in a claymation style, like a character from a stop-motion film.' },
  { label: 'Stained Glass', prompt: 'Transform the image into a vibrant stained glass window artwork.' },
  { label: 'Neon Noir', prompt: 'Reimagine the person in a neon noir art style, with dramatic shadows and bright, contrasting neon colors.' },
  { label: 'Egyptian', prompt: 'Depict the person as an ancient Egyptian pharaoh or deity with traditional attire.' },
  { label: 'Impressionist', prompt: 'Turn the photo into an impressionist painting with visible brush strokes and a focus on light.' },
  { label: 'Bodybuilder', prompt: 'Exaggerate the person\'s physique to look like a professional bodybuilder.' },
  { label: 'Mad Scientist', prompt: 'Transform the person into a mad scientist with wild hair, goggles, and a lab coat in a chaotic laboratory.' }
];